/* Generated by Virex Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Virex Runtime Library
void* virex_alloc(long size, long count);
void virex_free(void* ptr);
void virex_copy(void* dst, const void* src, long count);
void virex_set(void* dst, long value, long count);
void virex_print_i32(long value);
void virex_println_i32(long value);
void virex_print_bool(long value);
void virex_println_bool(long value);
void virex_print_str(const char* str);
void virex_println_str(const char* str);
void virex_exit(long code);
void virex_init_args(int argc, char** argv);


long fib(long);
long main();

long fib(long n) {
    long t0, t1, t2, t3, t4, t5, t6, t7, t8, t9;
    t0 = n;
    t1 = t0 <= 1;
    if (t1) goto L0;
    goto L1;
L0:;
    t2 = n;
    return t2;
    goto L2;
L1:;
L2:;
    t3 = n;
    t4 = t3 - 1;
    t5 = fib(t4);
    t6 = n;
    t7 = t6 - 2;
    t8 = fib(t7);
    t9 = t5 + t8;
    return t9;
}

long main() {
    long t0;
    long value;
    t0 = fib(10);
    value = t0;
    return 0;
}

