/* Generated by Virex Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Virex Runtime Library
void* virex_alloc(long size, long count);
void virex_free(void* ptr);
void virex_copy(void* dst, const void* src, long count);
void virex_set(void* dst, long value, long count);
void virex_print_i32(long value);
void virex_println_i32(long value);
void virex_print_bool(long value);
void virex_println_bool(long value);
void virex_print_str(const char* str);
void virex_println_str(const char* str);
void virex_exit(long code);
void virex_init_args(int argc, char** argv);

long main();

long main() {
    long t0, t1, t2;
    t0 = println_str(0);
    t1 = println_str(0);
    t2 = println_i32(42);
    return 0;
}

